### ISSUE TITLE
1.4 for 0.27.x missing

### ISSUE THREAD

**Issue by DanieleNoto** [Platoniq/decidim-module-navigation_maps#39]
Hi, I can't find a version available for 0.27.x. When I try to force 1.4 version I get an error about version missing. How can I use this in 0.27?

**Comment by fblupi** [comment]
The 1.4 version has not been uploaded to RubyGems, you need to install it from GitHub. Use this line in your Gemfile:

```ruby
gem "decidim-navigation_maps", git: "https://github.com/Platoniq/decidim-module-navigation_maps"
```

**Comment by DanieleNoto** [comment]
> The 1.4 version has not been uploaded to RubyGems, you need to install it from GitHub. Use this line in your Gemfile:
> 
> ```ruby
> gem "decidim-navigation_maps", git: "https://github.com/Platoniq/decidim-module-navigation_maps"
> ```

Thank you!
